import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import '@/styles/globals.css'

import {Metadata} from "next";

export const metadata: Metadata = {
    title: {
        default: "",
        template: "%s | hello world"
    },
    description: 'generated by next.js'
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
        <Header/>
        {children}
        <Footer/>
        </body>
        </html>
    )
}
