import Header from "@/app/components/Header";
import '../styles/globals.css'

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <head>

        </head>

        <body>
        <Header/>

        {children}

        <footer className="bg-green-700"
     
        >
            <p>Footer</p>
        </footer>
        </body>


        </html>
    )
}
