import Header
    from "@/app/pages/components/Header";
import Footer
    from "@/app/pages/components/Footer";
import '../styles/globals.css'

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {

    return (
        <html lang="en">
        <body>
        <Header/>
        {children}
        <Footer/>
        </body>


        </html>
    )
}
